FROM maven:3-adoptopenjdk-16 AS mvn-lib

# maven binary location: /usr/share/maven/bin/mvn
# maven lib location: /usr/share/maven

FROM openjdk:16-slim
COPY --from=mvn-lib /usr/share/maven /usr/share/maven