FROM openjdk:16-slim as jdk-lib

FROM ubuntu:20.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y firefox firefox-geckodriver

COPY --from=jdk-lib /usr/local/openjdk-16 /usr/local/openjdk-16

ENV PATH="/usr/local/openjdk-16/bin:${PATH}"