version: "3.9"

services:
  signoff-automator:
    container_name: signoff-automator
    image: maven-jdk-16
    volumes:
      - ./:/root/src
    working_dir: /root/src
    env_file: .env
    command: bash -c "java -Xmx1536M -jar ./target/signoffautomator-*.jar"