version: "3.9"

services:
  signoff-automator-v2:
    container_name: signoff-automator-v2
    image: ubuntu_ff
    volumes:
      - ./:/root/src/v2
    working_dir: /root/src/v2
    env_file: ../.env
    command: bash -c "./signoffautomator"